local Settings = {};
Settings.LeftoverRatio = 0.5;
Settings.FirstAidKit = {};
Settings.FirstAidKit.WeightModifier = 0.5;
Settings.Limits = {};
Settings.Limits.Default = 50;
Settings.Limits.FirstAidKitBandage = 20;
Settings.Limits.FirstAidKitDisinfectant = 1;
Settings.Limits.FirstAidKitPainkillers = 5;
return Settings;